//! Cross-language seal interop vector.
//!
//! The headline proof that a sealed blob produced by the browser's Web Crypto
//! API unseals byte-identically here. The fixture `webcrypto_vector.json` is a
//! genuine Web Crypto product: a fresh AES-256-GCM key wrapped with
//! RSA-OAEP-SHA256, 12-byte nonce, empty AAD, 16-byte tag appended, STANDARD
//! base64. It is NOT produced by this crate's `seal()`.
//!
//! The keypair in the fixture is a TEST-ONLY throwaway (generated by
//! apps/web/scripts/seal-vector.mjs); it has no production value. Regenerate the
//! fixture by running that script.

use boogy_seal::{unseal, SealEnvelope};
use secrecy::{ExposeSecret, SecretBox};
use serde::Deserialize;

#[derive(Deserialize)]
struct Vector {
    plaintext: String,
    private_pkcs8_b64: String,
    #[allow(dead_code)]
    public_spki_b64: String,
    envelope: SealEnvelope,
}

#[test]
fn unseals_webcrypto_vector() {
    use base64::{engine::general_purpose::STANDARD, Engine};

    let raw = include_str!("webcrypto_vector.json");
    let vector: Vector = serde_json::from_str(raw).expect("fixture is valid JSON");

    let priv_der = STANDARD
        .decode(vector.private_pkcs8_b64.as_bytes())
        .expect("private_pkcs8_b64 decodes");
    let priv_box = SecretBox::new(Box::new(priv_der));

    // The Web Crypto envelope must structurally pass the host's intermediary
    // gate (proves a real browser blob is accepted, not just our own seal()).
    let env_json = vector.envelope.to_json_bytes();
    SealEnvelope::parse_validated(&env_json)
        .expect("WebCrypto envelope passes parse_validated");

    let opened = unseal(&priv_box, &vector.envelope).expect("unseal succeeds");
    assert_eq!(
        opened.expose_secret().as_slice(),
        vector.plaintext.as_bytes(),
        "WebCrypto-sealed plaintext recovered byte-identically",
    );
}
