//! Guest-side protobuf RPC: status codes and the host handoff.
//!
//! The guest export is `handle(http-request) -> http-response`, and
//! `http-response` has no trailers field — so a status that must ride in HTTP/2
//! trailers cannot be returned directly. It rides reserved response headers the
//! host converts and strips — the same mechanism the platform's own
//! `x-boogy-stream` response header already uses. Guest→host only: the host
//! removes them, so they can neither reach a client nor be forged from
//! outside.

/// Include the protobuf message types `boogy-proto-build::compile()` generated
/// at build time, without naming `connectrpc` or `boogy-proto-build` in a
/// service's own source.
///
/// `boogy-proto-build` compiles a service's `.proto` files via `build.rs`
/// (`boogy_proto_build::compile(...)`) and is a **build-dependency only** —
/// it must never enter a guest's real dependency graph, since it pulls
/// `protox`/`connectrpc-build`/`prost`/`prettyplease`, the host-side codegen
/// toolchain. That means its own `include_generated!()` macro (if it had
/// one) would be uncallable from here: a path-invoked `macro_rules!`
/// resolves through the normal extern prelude, which only `[dependencies]`
/// populates — `[build-dependencies]` never does. `boogy-sdk` IS already a
/// `[dependencies]` entry of every service, and splicing in the generated
/// code needs nothing from `boogy-proto-build` itself (no function call,
/// just a path), so the macro lives here instead.
///
/// The file name below (`_connectrpc.rs`) is `boogy-proto-build::compile()`'s
/// own implementation detail — the fixed name it writes the include root to
/// (`boogy_proto_build::DESCRIPTOR_REL_PATH`'s codegen counterpart) — which
/// is exactly why this macro exists: a service author names neither that
/// file nor `connectrpc`, ever.
///
/// ```ignore, ignore_snippet: needs a build.rs-generated OUT_DIR/_connectrpc.rs to expand against
/// boogy_sdk::include_protos!();
/// use my_service::v1::{MyRequest, MyResponse};
/// ```
#[macro_export]
macro_rules! include_protos {
    () => {
        include!(concat!(env!("OUT_DIR"), "/_connectrpc.rs"));
    };
}

/// The 17 canonical gRPC status codes.
///
/// The numbering is wire protocol. Do not renumber.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum RpcCode {
    Ok = 0,
    Cancelled = 1,
    Unknown = 2,
    InvalidArgument = 3,
    DeadlineExceeded = 4,
    NotFound = 5,
    AlreadyExists = 6,
    PermissionDenied = 7,
    ResourceExhausted = 8,
    FailedPrecondition = 9,
    Aborted = 10,
    OutOfRange = 11,
    Unimplemented = 12,
    Internal = 13,
    Unavailable = 14,
    DataLoss = 15,
    Unauthenticated = 16,
}

// The reserved namespace's prefix, and the four
// header names built FROM it, are generated by ONE macro invocation over
// ONE literal -- not five independently-typed string literals that happen
// to agree today. Before this, `grpc_edge.rs::is_reserved_grpc_namespace`
// hardcoded its own copy of "x-boogy-grpc-" as the predicate that decides
// what a client can never inject and a guest can never forge; if these
// constants ever moved to a different prefix, that copy would silently
// stop matching and the strip would pass everything through. Generating
// both from the same macro call makes that divergence impossible to
// introduce by editing only one side.
macro_rules! reserved_grpc_header_constants {
    ($prefix:literal) => {
        /// The reserved namespace's prefix. Host-internal in BOTH
        /// directions: guest→host, stripped from what a guest emits; and
        /// host→guest, stripped from a caller's inbound headers at the
        /// entrance to dispatch, before the guest ever sees a
        /// caller-supplied header in this namespace. `grpc_edge.rs`'s own
        /// predicate matches THIS constant, not a private copy of the
        /// literal, specifically so the two cannot drift.
        pub const RESERVED_PREFIX: &str = $prefix;
        pub const STATUS_HEADER: &str = concat!($prefix, "status");
        pub const MESSAGE_HEADER: &str = concat!($prefix, "message");
        pub const TRAILER_PREFIX: &str = concat!($prefix, "trailer-");
        /// Reserved guest→host prefix for an ordinary RESPONSE header (as
        /// opposed to a trailer). Mirrors `TRAILER_PREFIX`
        /// deliberately: success and failure both encode metadata through
        /// the same two prefixes, so the host has exactly one place
        /// (`grpc_edge.rs::split_guest_headers`) that converts either into
        /// the wire-correct shape for the negotiated protocol, regardless
        /// of which arm produced them.
        pub const HEADER_PREFIX: &str = concat!($prefix, "header-");
        /// Reserved guest→host header carrying ONE structured error detail
        /// — gRPC's rich error model, `repeated google.protobuf.Any`
        /// on the wire. Unlike `HEADER_PREFIX`/`TRAILER_PREFIX` (a prefix a
        /// caller-chosen KEY is appended to), this is a single fixed name
        /// used REPEATEDLY, once per detail, in order: a detail has no key of
        /// its own to append, only an ordered `(type_name, bytes)` pair, and
        /// `RpcStatus`'s guest-side `headers`/`trailers` fields are a plain
        /// `Vec<(String, String)>` (not a real header map), so pushing the
        /// same name twice is exactly as well-formed as pushing it once —
        /// order survives because the Vec's push order does.
        pub const DETAIL_HEADER: &str = concat!($prefix, "detail");
    };
}
reserved_grpc_header_constants!("x-boogy-grpc-");

/// Separates a detail's type name from its base64-encoded payload inside
/// one `DETAIL_HEADER` value: `"{type_name}{DETAIL_SEPARATOR}{base64}"`.
/// Exported (not a private literal re-typed on the host side) for the same
/// reason `RESERVED_PREFIX` is: `grpc_edge.rs`'s parser matches THIS
/// constant, so the encoder and decoder cannot drift apart by one side
/// changing the character alone. `|` is safe on both sides of the split —
/// a protobuf full type name is `[A-Za-z_][A-Za-z0-9_]*` segments joined by
/// `.` (never `|`), a `type.googleapis.com/...` URL adds only `/` and `.`,
/// and the base64 alphabet this module emits (`STANDARD_NO_PAD`) is
/// `[A-Za-z0-9+/]` — none of the three ever produces a literal `|`, so
/// splitting on the FIRST occurrence is unambiguous.
pub const DETAIL_SEPARATOR: char = '|';

/// The base64 form the Connect protocol's error-detail `value` field uses:
/// unpadded standard alphabet. Matches `connectrpc::error::detail_b64`
/// (host-side, not reachable from here — a guest depends on `buffa` only,
/// never `connectrpc`) byte for byte, which is what lets the host pass a
/// guest-encoded detail value straight into `ErrorDetail.value` with no
/// re-encoding step.
fn encode_detail_value(bytes: &[u8]) -> String {
    use base64::Engine as _;
    base64::engine::general_purpose::STANDARD_NO_PAD.encode(bytes)
}

/// A call's terminal status plus any response metadata: headers to send
/// before the body, and trailers to send after it. Used for BOTH arms —
/// `RpcStatus::ok()` is what a successful [`GrpcDispatcher::method`]
/// handler's `Response<R>` gets folded into before `finish()` encodes it,
/// and a non-OK status is what an `Err(RpcStatus)` handler return produces
/// directly. One type, one encoding
/// (`into_headers`) for both, so the wire mechanism never depends on
/// which arm is running.
///
/// `#[non_exhaustive]`: this is a published SDK type, and this field list
/// has already grown twice (`headers`; before that just
/// `code`/`message`/`trailers`). A
/// downstream struct-literal construction breaks on every future field
/// addition otherwise — cheap to pay now, pre-1.0, before an external
/// consumer exists to break.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct RpcStatus {
    pub code: RpcCode,
    pub message: String,
    pub headers: Vec<(String, String)>,
    pub trailers: Vec<(String, String)>,
    /// Structured error details — gRPC's rich error model
    /// (`repeated google.protobuf.Any`). Each entry is `(type_name,
    /// encoded_bytes)`; see [`with_detail`](Self::with_detail) /
    /// [`with_detail_bytes`](Self::with_detail_bytes) for how they're built
    /// and [`into_headers`](Self::into_headers) for the wire encoding.
    pub details: Vec<(String, Vec<u8>)>,
}

impl RpcStatus {
    pub fn new(code: RpcCode, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
            headers: Vec::new(),
            trailers: Vec::new(),
            details: Vec::new(),
        }
    }
    pub fn ok() -> Self {
        Self {
            code: RpcCode::Ok,
            message: String::new(),
            headers: Vec::new(),
            trailers: Vec::new(),
            details: Vec::new(),
        }
    }
    pub fn not_found(m: impl Into<String>) -> Self { Self::new(RpcCode::NotFound, m) }
    pub fn invalid_argument(m: impl Into<String>) -> Self { Self::new(RpcCode::InvalidArgument, m) }
    pub fn permission_denied(m: impl Into<String>) -> Self { Self::new(RpcCode::PermissionDenied, m) }
    pub fn internal(m: impl Into<String>) -> Self { Self::new(RpcCode::Internal, m) }
    pub fn unimplemented(m: impl Into<String>) -> Self { Self::new(RpcCode::Unimplemented, m) }
    /// Deliberately message-free: an authentication failure that explains
    /// itself is an enumeration oracle.
    pub fn unauthenticated() -> Self { Self::new(RpcCode::Unauthenticated, "") }

    /// Attach a response header (sent before the body). Available on any
    /// status, OK or not — a failed call can name a request id too.
    ///
    /// A few names belong to the transport and are dropped rather than sent:
    /// body-framing and hop-by-hop names (`content-type`, `content-length`,
    /// `transfer-encoding`, …), the terminal `grpc-status`/`grpc-message`
    /// channel — the call's status is the `RpcStatus` itself, not a header —
    /// and the reserved `x-boogy-grpc-*` prefix this module owns. The same
    /// rule applies to `with_trailer`, and to `Response`'s pair of the same
    /// names. Everything else is forwarded verbatim.
    pub fn with_header(mut self, k: impl Into<String>, v: impl Into<String>) -> Self {
        self.headers.push((k.into(), v.into()));
        self
    }

    /// Attach a response trailer (sent after the body). Same reserved-name
    /// rule as `with_header`.
    pub fn with_trailer(mut self, k: impl Into<String>, v: impl Into<String>) -> Self {
        self.trailers.push((k.into(), v.into()));
        self
    }

    /// Attach a structured error detail — gRPC's rich error model: a
    /// `repeated google.protobuf.Any`, each entry a type name plus its
    /// encoded bytes. Packs a TYPED message (mirrors connectrpc's own
    /// `ErrorDetail::from_message` on the host side, which this call
    /// eventually feeds) rather than asking a handler to hand-build an
    /// `Any` — design-lenses lens 6: a handler that had to encode `Any` by
    /// hand would be writing this SDK's own job. Ordinary application use
    /// (a validation failure naming the offending field, a quota error
    /// carrying the limit and reset time) always has a concrete Rust type
    /// to pack, so this is the path to reach for.
    ///
    /// `type_name` may be the message's bare fully-qualified name (e.g.
    /// `notes.v1.QuotaExceeded`) or an already-prefixed
    /// `type.googleapis.com/...` URL (a generated type's own `T::TYPE_URL`
    /// const, if one is in scope) — both flow through unchanged; the host's
    /// gRPC-wire encoder prefixes a bare name automatically and passes an
    /// already-prefixed one through, while the Connect JSON encoder uses
    /// whichever was given verbatim, matching upstream's own `Any`-URL
    /// convention. Available whether `self` is `ok()` or an error — a
    /// detail on a *successful* call has no defined meaning on the wire
    /// (`google.rpc.Status.details` is part of an ERROR status), so a
    /// detail attached to an OK status is silently dropped by
    /// `into_headers` rather than sent.
    ///
    /// Multiple calls append, in order — the wire's `repeated Any` is a
    /// list, not a map, so there is no last-write-wins collapsing the way
    /// `with_header`/`with_trailer`'s KEYED metadata could in principle
    /// have.
    pub fn with_detail(mut self, type_name: impl Into<String>, message: &impl buffa::Message) -> Self {
        self.details.push((type_name.into(), message.encode_to_vec()));
        self
    }

    /// The raw-bytes escape hatch: attach a detail whose bytes are ALREADY
    /// protobuf-encoded, for a handler forwarding an opaque `Any` it did
    /// not itself construct — a service relaying another service's error,
    /// or (the concrete case that forced this method to exist)
    /// `conformance-server` echoing a caller-supplied
    /// `Error.details: repeated google.protobuf.Any` byte for byte, where
    /// the type is whatever the CALLER declared and there is no local Rust
    /// type to pack. Prefer [`with_detail`](Self::with_detail) whenever the
    /// caller controls the message type — that path can never emit bytes
    /// that don't match the type name it claims; this one trusts the
    /// caller to have paired them correctly, the same honesty tradeoff
    /// `google.protobuf.Any` itself makes.
    pub fn with_detail_bytes(mut self, type_name: impl Into<String>, encoded: Vec<u8>) -> Self {
        self.details.push((type_name.into(), encoded));
        self
    }

    /// Render as the reserved guest→host response headers.
    pub fn into_headers(self) -> Vec<(String, String)> {
        let mut out = vec![(STATUS_HEADER.to_string(), (self.code as i32).to_string())];
        if !self.message.is_empty() {
            out.push((MESSAGE_HEADER.to_string(), self.message));
        }
        for (k, v) in self.headers {
            out.push((format!("{HEADER_PREFIX}{k}"), v));
        }
        for (k, v) in self.trailers {
            out.push((format!("{TRAILER_PREFIX}{k}"), v));
        }
        // `google.rpc.Status.details` is meaningful only on a non-OK
        // status — an OK status has no `Status` message on the wire at
        // all (gRPC's own trailers-only success path never builds one),
        // so a detail attached to `ok()` has nowhere to go. Silently
        // dropping it here (rather than sending it and letting the host
        // discard it, or panicking) keeps the guest-side encoding total:
        // `into_headers` never fails, and `RpcStatus::ok().with_detail(..)`
        // is a caller mistake, not a wire-protocol question.
        if self.code != RpcCode::Ok {
            for (type_name, bytes) in self.details {
                // Fix round 1 (review): `split_guest_headers` on the host
                // splits on the FIRST `DETAIL_SEPARATOR` -- a type name that
                // itself contains one is not rejected there, it is
                // HALF-PARSED: the tail of the type name silently becomes a
                // prefix of the base64 payload, producing a fabricated
                // type_url (gRPC's `encode_any` sees no `/`, so it still
                // prefixes the truncated name) with a value that fails to
                // decode and is dropped. Reachable exactly where it hurts:
                // `with_detail_bytes`' own doc names forwarding an untrusted
                // caller-supplied type_url as the intended use, and
                // `conformance-server::error_to_status` does exactly that
                // with client-controlled `Error.details[].type_url`. Reject
                // (drop, don't half-parse) here at the encode site instead
                // of teaching `split_guest_headers` to guess intent from a
                // corrupted value it can no longer recover the boundary
                // from. Consuming-`self` stays a total builder -- no
                // `Result` -- because a `Result` in this chain would tax
                // every well-formed caller to punish an unreachable one; a
                // dropped detail is not silent, since the guest's own
                // `warn!` lands in the same guest-log ring buffer the owner
                // already reads everything else through.
                if type_name.is_empty() {
                    crate::log::warn!(
                        "RpcStatus::with_detail/with_detail_bytes: dropping a \
                         detail with an empty type name"
                    );
                    continue;
                }
                if type_name.contains(DETAIL_SEPARATOR) {
                    crate::log::warn!(
                        "RpcStatus::with_detail/with_detail_bytes: dropping detail \
                         '{type_name}' -- its type name contains the reserved \
                         '{DETAIL_SEPARATOR}' wire separator (a well-formed \
                         protobuf type name or type.googleapis.com/ URL never \
                         does); this is very likely an untrusted type name \
                         forwarded unchecked -- see with_detail_bytes' own doc"
                    );
                    continue;
                }
                let value = format!("{type_name}{DETAIL_SEPARATOR}{}", encode_detail_value(&bytes));
                out.push((DETAIL_HEADER.to_string(), value));
            }
        }
        out
    }
}

/// A successful RPC's typed body plus any response headers/trailers to
/// attach. What a [`GrpcDispatcher::method`] handler returns on
/// the `Ok` arm instead of the bare `R`, so a call that SUCCEEDS has the
/// same channel for metadata a call that fails already had via
/// `RpcStatus::with_trailer`/`with_header`.
///
/// Deliberately mirrors `connectrpc`'s own `Response<B>` (`.with_header`/
/// `.with_trailer` builders) — an author who has used the upstream
/// library recognizes this immediately, and one who hasn't learns a shape
/// that transfers if they ever do. It carries no status `code`: returning
/// `Ok(Response<R>)` at all IS the success signal, so there is no field
/// here that could disagree with the `Result` it's wrapped in.
///
/// `#[non_exhaustive]` for the same reason as `RpcStatus` above — public,
/// pre-1.0, and cheapest to mark now rather than after a field addition
/// breaks a downstream struct literal.
#[non_exhaustive]
pub struct Response<R> {
    pub body: R,
    pub headers: Vec<(String, String)>,
    pub trailers: Vec<(String, String)>,
}

impl<R> Response<R> {
    /// Bare body, no metadata — the common case.
    pub fn new(body: R) -> Self {
        Self { body, headers: Vec::new(), trailers: Vec::new() }
    }

    /// Attach a response header (sent before the body). Same reserved-name
    /// rule as `RpcStatus::with_header`.
    pub fn with_header(mut self, k: impl Into<String>, v: impl Into<String>) -> Self {
        self.headers.push((k.into(), v.into()));
        self
    }

    /// Attach a response trailer (sent after the body). Same reserved-name
    /// rule as `RpcStatus::with_header`.
    pub fn with_trailer(mut self, k: impl Into<String>, v: impl Into<String>) -> Self {
        self.trailers.push((k.into(), v.into()));
        self
    }
}

/// A handler with nothing to attach writes `Ok(msg.into())` (or
/// `Ok(msg)` where the return type makes the conversion unambiguous)
/// instead of the more verbose `Ok(Response::new(msg))`.
impl<R> From<R> for Response<R> {
    fn from(body: R) -> Self {
        Self::new(body)
    }
}

use crate::response;
use crate::router::Req;

/// Header the host sets to tell the guest which codec the client negotiated.
/// Value is `proto` (the default assumed when the header is absent — a
/// missing header must not silently misinterpret a binary body as JSON) or
/// `json` (Connect+JSON).
pub const CODEC_HEADER: &str = "x-boogy-rpc";

/// Extract the method name — the final path segment.
///
/// The host routes on the mounted path pattern (`/{service}/{method}`)
/// alone; it never inspects the descriptor, so this is the guest's only
/// way to learn which method was called.
pub fn method_from_path(path: &str) -> Option<&str> {
    let last = path.rsplit('/').next()?;
    if last.is_empty() { None } else { Some(last) }
}

/// One registered method's erased codec-and-dispatch step's SUCCESS
/// output: the encoded body plus whatever headers/trailers the handler's
/// `Response<R>` carried — `R` itself doesn't survive erasure, but its
/// metadata must, or the whole point of the `Ok` arm carrying metadata (a
/// successful call can set response headers/trailers) would be lost at
/// exactly this boundary.
struct EncodedOk {
    body: Vec<u8>,
    headers: Vec<(String, String)>,
    trailers: Vec<(String, String)>,
}

/// One registered method's erased codec-and-dispatch step: decode the
/// request bytes (proto or JSON, per the `bool`), run the typed handler,
/// re-encode the result. Boxed so `GrpcDispatcher::methods` can hold a
/// `Vec` of heterogeneous `P`/`R` pairs behind one concrete type.
type Erased = Box<dyn Fn(&mut Req<'_>, &[u8], bool) -> Result<EncodedOk, RpcStatus>>;

/// Typed method dispatch for one protobuf service, over opaque message
/// bytes the host has already stripped of framing (length-prefix, HTTP/2
/// or Connect-JSON envelope, compression) — this only ever sees the bare
/// message.
///
/// Deliberately shaped like [`crate::rpc::Dispatcher`] — same registration
/// chain, same `Fn(P) -> Result<R, E>` handler shape — so a service author
/// meets one pattern, not two, and the same business-logic function can
/// usually back a REST, JSON-RPC, and protobuf method without reshaping.
pub struct GrpcDispatcher {
    service: String,
    methods: Vec<(String, Erased)>,
}

impl GrpcDispatcher {
    pub fn new(service: &str) -> Self {
        Self { service: service.to_string(), methods: Vec::new() }
    }

    pub fn service_name(&self) -> &str {
        &self.service
    }

    /// Register a typed method handler.
    ///
    /// `P`/`R` decode/encode as protobuf binary by default; when the host
    /// marks the request `x-boogy-rpc: json` they decode/encode instead
    /// through the SAME `serde::Serialize`/`Deserialize` impls buffa's
    /// codegen emits on every generated message (Connect+JSON, protobuf's
    /// canonical JSON mapping — not an ad hoc struct-field dump), so a
    /// service author never writes a JSON path by hand.
    ///
    /// The success arm returns `Response<R>`, not a bare `R`:
    /// wrap a plain body with `Response::new(body)` (or `.into()`), and
    /// chain `.with_header(...)`/`.with_trailer(...)` when the call needs
    /// to set response metadata — a pagination cursor, a rate-limit
    /// header, a request id. A handler with nothing to attach is one
    /// extra `Response::new(...)` / `.into()` versus returning `R`
    /// directly.
    pub fn method<P, R, F>(mut self, name: &str, f: F) -> Self
    where
        P: buffa::Message + Default + serde::de::DeserializeOwned,
        R: buffa::Message + serde::Serialize,
        F: Fn(&mut Req<'_>, P) -> Result<Response<R>, RpcStatus> + 'static,
    {
        let erased: Erased = Box::new(move |req, bytes, json| {
            let msg: P = if json {
                serde_json::from_slice(bytes)
                    .map_err(|e| RpcStatus::invalid_argument(e.to_string()))?
            } else {
                P::decode_from_slice(bytes)
                    .map_err(|e| RpcStatus::invalid_argument(e.to_string()))?
            };
            let Response { body, headers, trailers } = f(req, msg)?;
            let body = if json {
                serde_json::to_vec(&body).map_err(|e| RpcStatus::internal(e.to_string()))?
            } else {
                body.encode_to_vec()
            };
            Ok(EncodedOk { body, headers, trailers })
        });
        self.methods.push((name.to_string(), erased));
        self
    }

    /// The status returned when no registered method matches `name`.
    pub fn status_for_missing_method(&self, name: &str) -> RpcStatus {
        RpcStatus::unimplemented(format!("method not found: {}/{name}", self.service))
    }

    /// Decode, dispatch, encode. `req.request.body` is the bare message —
    /// the host has already stripped the envelope and decompressed it.
    /// Takes `&mut Req<'_>` (not `&Request`, unlike
    /// [`crate::rpc::Dispatcher::handle`]) so a registered handler can
    /// reach guards' `Ctx` state the same way any other route handler does.
    pub fn handle(&self, req: &mut Req<'_>) -> response::HttpResponse {
        let json = req
            .header(CODEC_HEADER)
            .map(|v| v.eq_ignore_ascii_case("json"))
            .unwrap_or(false);

        let Some(name) = method_from_path(req.path()).map(str::to_string) else {
            return finish(Vec::new(), self.status_for_missing_method(""));
        };

        let Some((_, handler)) = self.methods.iter().find(|(m, _)| *m == name) else {
            return finish(Vec::new(), self.status_for_missing_method(&name));
        };

        // Owned copy: `handler` needs `&mut req` below, which would
        // otherwise conflict with a borrow of `req.body()` still live.
        let body = req.body().map(<[u8]>::to_vec).unwrap_or_default();
        match handler(req, &body, json) {
            Ok(EncodedOk { body, headers, trailers }) => {
                // Same `RpcStatus` -> `finish()` path the error arm uses
                // below: a successful call's headers/trailers are folded
                // into an OK status rather than threaded through a
                // parallel mechanism, so the host's decoder
                // (`grpc_edge.rs::split_guest_headers`) never has to care
                // which arm produced a given reserved header.
                let mut status = RpcStatus::ok();
                status.headers = headers;
                status.trailers = trailers;
                finish(body, status)
            }
            Err(status) => finish(Vec::new(), status),
        }
    }
}

/// Build the guest response: body is the bare encoded message, status rides
/// the reserved headers (see the module doc comment for why). Always HTTP
/// 200 at the guest→host boundary — the host chooses the real wire status
/// per protocol (Connect uses HTTP status codes for some errors, gRPC never
/// does), which is a decision this layer doesn't have enough information
/// to make.
fn finish(body: Vec<u8>, status: RpcStatus) -> response::HttpResponse {
    let mut headers = vec![("content-type".to_string(), "application/octet-stream".to_string())];
    headers.extend(status.into_headers());
    response::HttpResponse { status: 200, headers, body: Some(body) }
}

#[cfg(test)]
mod tests {
    use super::*;
    use buffa::Message as _;

    // The five reserved header names are built FROM
    // `RESERVED_PREFIX` by one macro invocation, not typed out separately
    // -- this pins that they actually agree, so a future edit to the macro
    // (or to the literal it's invoked with) that broke the relationship
    // would be caught here, at the source, rather than only in whichever
    // downstream predicate (`grpc_edge.rs::is_reserved_grpc_namespace`)
    // happens to read `RESERVED_PREFIX`.
    #[test]
    fn the_five_reserved_names_are_built_from_reserved_prefix() {
        assert_eq!(RESERVED_PREFIX, "x-boogy-grpc-");
        assert!(STATUS_HEADER.starts_with(RESERVED_PREFIX));
        assert!(MESSAGE_HEADER.starts_with(RESERVED_PREFIX));
        assert!(HEADER_PREFIX.starts_with(RESERVED_PREFIX));
        assert!(TRAILER_PREFIX.starts_with(RESERVED_PREFIX));
        assert!(DETAIL_HEADER.starts_with(RESERVED_PREFIX));
        assert_eq!(STATUS_HEADER, "x-boogy-grpc-status");
        assert_eq!(MESSAGE_HEADER, "x-boogy-grpc-message");
        assert_eq!(HEADER_PREFIX, "x-boogy-grpc-header-");
        assert_eq!(TRAILER_PREFIX, "x-boogy-grpc-trailer-");
        assert_eq!(DETAIL_HEADER, "x-boogy-grpc-detail");
    }

    #[test]
    fn ok_status_encodes_as_zero_with_no_message() {
        let hs = RpcStatus::ok().into_headers();
        assert_eq!(hs, vec![(STATUS_HEADER.to_string(), "0".to_string())]);
    }

    #[test]
    fn error_status_carries_code_and_message() {
        let hs = RpcStatus::not_found("no such note").into_headers();
        assert!(hs.contains(&(STATUS_HEADER.to_string(), "5".to_string())));
        assert!(hs.contains(&(MESSAGE_HEADER.to_string(), "no such note".to_string())));
    }

    #[test]
    fn trailing_metadata_is_prefixed() {
        let hs = RpcStatus::ok().with_trailer("retry-count", "2").into_headers();
        assert!(hs.contains(&(
            format!("{TRAILER_PREFIX}retry-count"),
            "2".to_string()
        )));
    }

    // A SUCCESSFUL status must be able to carry response
    // headers too, through the same reserved-prefix mechanism trailers
    // already use. Before this task `RpcStatus` had no `headers` field and
    // no `with_header` method at all -- this is new surface, not a change
    // to an existing one.
    #[test]
    fn ok_status_can_carry_response_headers_alongside_trailers() {
        let hs = RpcStatus::ok()
            .with_header("x-request-id", "abc123")
            .with_trailer("x-server-timing", "12ms")
            .into_headers();
        assert!(
            hs.contains(&(format!("{HEADER_PREFIX}x-request-id"), "abc123".to_string())),
            "expected a header-prefix entry; got {hs:?}"
        );
        assert!(
            hs.contains(&(format!("{TRAILER_PREFIX}x-server-timing"), "12ms".to_string())),
            "expected a trailer-prefix entry; got {hs:?}"
        );
        // Still carries the OK status -- headers/trailers are additive, not
        // a replacement for the status header.
        assert!(hs.contains(&(STATUS_HEADER.to_string(), "0".to_string())));
    }

    // A status must be able to carry a structured error
    // DETAIL -- gRPC's rich error model, `repeated google.protobuf.Any`.
    // Before this task `RpcStatus` had no `details` field and no
    // `with_detail`/`with_detail_bytes` methods at all, so a handler had no
    // way to name the offending field on a validation failure or carry a
    // limit/reset-time on a quota error.
    #[test]
    fn error_status_can_carry_a_typed_detail() {
        let detail = TestMsg { text: "field: name is required".to_string() };
        let hs = RpcStatus::invalid_argument("bad request")
            .with_detail("test.v1.TestMsg", &detail)
            .into_headers();
        let expected_value = format!(
            "test.v1.TestMsg{DETAIL_SEPARATOR}{}",
            encode_detail_value(&detail.encode_to_vec()),
        );
        assert!(
            hs.contains(&(DETAIL_HEADER.to_string(), expected_value.clone())),
            "expected a detail header carrying '{expected_value}'; got {hs:?}"
        );
        // Still carries the real status -- a detail is additive, not a
        // replacement for the code/message.
        assert!(hs.contains(&(STATUS_HEADER.to_string(), "3".to_string())));
    }

    #[test]
    fn error_status_can_carry_a_raw_bytes_detail() {
        // The escape hatch: bytes already encoded, no local buffa::Message
        // to pack -- the shape `conformance-server` needs to forward an
        // opaque caller-supplied `Any` byte for byte.
        let hs = RpcStatus::internal("boom")
            .with_detail_bytes("type.googleapis.com/google.protobuf.Any", vec![1, 2, 3])
            .into_headers();
        let expected_value = format!(
            "type.googleapis.com/google.protobuf.Any{DETAIL_SEPARATOR}{}",
            encode_detail_value(&[1, 2, 3]),
        );
        assert!(
            hs.contains(&(DETAIL_HEADER.to_string(), expected_value.clone())),
            "got {hs:?}"
        );
    }

    #[test]
    fn multiple_details_append_in_order() {
        // The wire's repeated Any is a LIST -- unlike with_header/
        // with_trailer's keyed metadata, there is no last-write-wins
        // collapsing to worry about, and order must survive.
        let hs = RpcStatus::internal("boom")
            .with_detail_bytes("a.A", vec![1])
            .with_detail_bytes("b.B", vec![2])
            .into_headers();
        let detail_headers: Vec<&(String, String)> =
            hs.iter().filter(|(k, _)| k == DETAIL_HEADER).collect();
        assert_eq!(detail_headers.len(), 2, "got {hs:?}");
        assert!(detail_headers[0].1.starts_with("a.A|"), "got {:?}", detail_headers[0]);
        assert!(detail_headers[1].1.starts_with("b.B|"), "got {:?}", detail_headers[1]);
    }

    #[test]
    fn a_detail_on_an_ok_status_is_dropped_not_sent() {
        // google.rpc.Status.details is part of an ERROR status -- there is
        // no wire representation for a detail on a successful call
        // (gRPC's trailers-only success path never builds a Status
        // message at all), so into_headers must not emit one rather than
        // sending a value the host/client have nowhere correct to put.
        let hs = RpcStatus::ok().with_detail_bytes("a.A", vec![1]).into_headers();
        assert!(
            !hs.iter().any(|(k, _)| k == DETAIL_HEADER),
            "an OK status must not emit a detail header; got {hs:?}"
        );
    }

    // Fix round 1 (review, Important 1): a type name containing the wire
    // separator must be REJECTED, not half-parsed. Before this fix,
    // `with_detail_bytes("a|b", bytes)` produced `"a|b|<base64>"`, which the
    // host's `split_once` on the FIRST separator turns into type_name="a",
    // value="b|<base64>" -- a fabricated type and a value that fails to
    // base64-decode. Reachable via the exact relay path
    // `with_detail_bytes`'s own doc recommends (forwarding an untrusted
    // caller-supplied type_url).
    #[test]
    fn a_type_name_containing_the_separator_is_dropped_not_half_parsed() {
        let bad = format!("a{DETAIL_SEPARATOR}b");
        let hs = RpcStatus::internal("boom").with_detail_bytes(bad, vec![1, 2, 3]).into_headers();
        assert!(
            !hs.iter().any(|(k, _)| k == DETAIL_HEADER),
            "a type name containing the separator must be dropped entirely, \
             not emitted half-parsed; got {hs:?}"
        );
        // The rest of the status (code/message) must still be delivered --
        // dropping a malformed DETAIL must never take the whole status with it.
        assert!(hs.iter().any(|(k, v)| k == STATUS_HEADER && v == "13"));
    }

    #[test]
    fn an_empty_type_name_is_dropped() {
        let hs = RpcStatus::internal("boom").with_detail_bytes("", vec![1]).into_headers();
        assert!(
            !hs.iter().any(|(k, _)| k == DETAIL_HEADER),
            "an empty type name must be dropped; got {hs:?}"
        );
    }

    #[test]
    fn a_well_formed_type_name_with_a_typed_detail_still_survives_validation() {
        // Not every detail goes through with_detail_bytes -- with_detail's
        // typed path must pass the same validation without being penalized
        // for it when the caller behaved.
        let detail = TestMsg { text: "ok".to_string() };
        let hs = RpcStatus::internal("boom").with_detail("a.A", &detail).into_headers();
        assert!(
            hs.iter().any(|(k, v)| k == DETAIL_HEADER && v.starts_with("a.A|")),
            "a well-formed detail must still be emitted; got {hs:?}"
        );
    }

    #[test]
    fn codes_match_the_canonical_grpc_numbering() {
        // These numbers are wire protocol, not an internal choice. Getting one
        // wrong silently mislabels every failure of that class for every client.
        assert_eq!(RpcCode::Ok as i32, 0);
        assert_eq!(RpcCode::Cancelled as i32, 1);
        assert_eq!(RpcCode::InvalidArgument as i32, 3);
        assert_eq!(RpcCode::DeadlineExceeded as i32, 4);
        assert_eq!(RpcCode::NotFound as i32, 5);
        assert_eq!(RpcCode::PermissionDenied as i32, 7);
        assert_eq!(RpcCode::Unimplemented as i32, 12);
        assert_eq!(RpcCode::Internal as i32, 13);
        assert_eq!(RpcCode::Unauthenticated as i32, 16);
    }

    // ─── GrpcDispatcher ─────────────────────────────────────────────────

    #[test]
    fn unknown_method_is_unimplemented_not_a_404() {
        // The host routes on path alone and never consults the descriptor, so
        // the guest is what answers for an unknown method. Returning 404 here
        // would surface to a gRPC client as a transport error rather than
        // status 12, which is a different and much less debuggable failure.
        let d = GrpcDispatcher::new("notes.v1.NotesService");
        let status = d.status_for_missing_method("NoSuchMethod");
        assert_eq!(status.code, RpcCode::Unimplemented);
        assert!(status.message.contains("NoSuchMethod"));
    }

    #[test]
    fn method_name_is_the_last_path_segment() {
        assert_eq!(method_from_path("/notes.v1.NotesService/GetNote"), Some("GetNote"));
        assert_eq!(method_from_path("notes.v1.NotesService/GetNote"), Some("GetNote"));
        assert_eq!(method_from_path("/GetNote"), Some("GetNote"));
        assert_eq!(method_from_path("/"), None);
        assert_eq!(method_from_path(""), None);
    }

    // A minimal hand-written `Message` impl for exercising `GrpcDispatcher`
    // without a generated proto crate — that codegen is a build-time
    // toolchain (protox + connectrpc-build) that isn't wired into
    // boogy-sdk's own build, so there is no generated message type
    // available here. The binary codec below is a deliberate no-op stub —
    // same shape as buffa's own `__doctest_fixtures::Person` — so it
    // proves nothing about wire-format correctness (that's buffa's job,
    // and the codegen's own for the generated types); it exists only to
    // exercise `GrpcDispatcher::handle`'s routing/dispatch/status-header
    // machinery. The JSON side, by contrast, uses a real `serde` derive,
    // so `handle_dispatches_the_json_codec_and_round_trips_the_field`
    // genuinely proves the field value survives the codec.
    #[derive(Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
    struct TestMsg {
        text: String,
    }

    impl buffa::DefaultInstance for TestMsg {
        fn default_instance() -> &'static Self {
            static INST: std::sync::OnceLock<TestMsg> = std::sync::OnceLock::new();
            INST.get_or_init(TestMsg::default)
        }
    }

    impl buffa::Message for TestMsg {
        fn compute_size(&self, _cache: &mut buffa::SizeCache) -> u32 {
            0
        }
        fn write_to(&self, _cache: &mut buffa::SizeCache, _buf: &mut impl buffa::EncodeSink) {}
        fn merge_field(
            &mut self,
            tag: buffa::encoding::Tag,
            buf: &mut impl buffa::bytes::Buf,
            _ctx: buffa::DecodeContext<'_>,
        ) -> Result<(), buffa::DecodeError> {
            buffa::encoding::skip_field(tag, buf)
        }
        fn clear(&mut self) {
            *self = Self::default();
        }
    }

    fn echo(_req: &mut Req<'_>, msg: TestMsg) -> Result<Response<TestMsg>, RpcStatus> {
        Ok(msg.into())
    }

    fn test_req(path: &str, headers: Vec<(String, String)>, body: Vec<u8>) -> crate::Request {
        crate::Request {
            method: "POST".to_string(),
            path: path.to_string(),
            headers,
            body: Some(body),
            path_params: vec![],
            query_params: vec![],
        }
    }

    #[test]
    fn handle_dispatches_to_the_registered_method() {
        let d = GrpcDispatcher::new("test.EchoService").method("Echo", echo);
        let request = test_req("/test.EchoService/Echo", vec![], vec![]);
        let params = crate::router::Params::from_pairs(vec![]);
        let mut req = Req { request: &request, params: &params, ctx: crate::ctx::Ctx::new() };
        let resp = d.handle(&mut req);
        // gRPC status rides reserved headers, not the HTTP status — see the
        // module doc comment on why (`http-response` has no trailers field).
        assert_eq!(resp.status, 200);
        assert!(
            resp.headers.contains(&(STATUS_HEADER.to_string(), "0".to_string())),
            "successful dispatch must carry OK (0) status header; got {:?}",
            resp.headers
        );
    }

    #[test]
    fn handle_returns_unimplemented_for_an_unregistered_method() {
        let d = GrpcDispatcher::new("test.EchoService"); // no .method() calls
        let request = test_req("/test.EchoService/NoSuchMethod", vec![], vec![]);
        let params = crate::router::Params::from_pairs(vec![]);
        let mut req = Req { request: &request, params: &params, ctx: crate::ctx::Ctx::new() };
        let resp = d.handle(&mut req);
        assert_eq!(resp.status, 200);
        assert!(resp.headers.contains(&(STATUS_HEADER.to_string(), "12".to_string())));
        assert!(
            resp.headers.iter().any(|(k, v)| k == MESSAGE_HEADER && v.contains("NoSuchMethod")),
            "missing-method status must name the method that was missing; got {:?}",
            resp.headers
        );
    }

    // The gap this closes. Before it, `GrpcDispatcher`'s
    // success arm was hardcoded to `finish(bytes, RpcStatus::ok())` -- a
    // handler returning `Ok(R)` had no channel for response metadata at
    // all, so a SUCCESSFUL call could never set a header or a trailer
    // (only a FAILED one could, via `RpcStatus::with_trailer`). This
    // handler succeeds and sets both; the dispatcher must surface both as
    // reserved headers on the 200 response, the exact same encoding the
    // error arm already uses (`HEADER_PREFIX`/`TRAILER_PREFIX`), which is
    // what lets the host convert them identically regardless of which arm
    // produced them.
    fn echo_with_metadata(_req: &mut Req<'_>, msg: TestMsg) -> Result<Response<TestMsg>, RpcStatus> {
        Ok(Response::new(msg)
            .with_header("x-request-id", "req-42")
            .with_trailer("x-server-timing", "7ms"))
    }

    #[test]
    fn a_successful_call_can_set_a_response_header_and_a_trailer() {
        let d = GrpcDispatcher::new("test.EchoService").method("Echo", echo_with_metadata);
        let body = TestMsg { text: "hi".to_string() }.encode_to_vec();
        let request = test_req("/test.EchoService/Echo", vec![], body);
        let params = crate::router::Params::from_pairs(vec![]);
        let mut req = Req { request: &request, params: &params, ctx: crate::ctx::Ctx::new() };
        let resp = d.handle(&mut req);

        assert!(
            resp.headers.contains(&(STATUS_HEADER.to_string(), "0".to_string())),
            "a successful call must still carry OK status; got {:?}",
            resp.headers
        );
        assert!(
            resp.headers.contains(&(
                format!("{HEADER_PREFIX}x-request-id"),
                "req-42".to_string()
            )),
            "expected the response header to survive dispatch; got {:?}",
            resp.headers
        );
        assert!(
            resp.headers.contains(&(
                format!("{TRAILER_PREFIX}x-server-timing"),
                "7ms".to_string()
            )),
            "expected the trailer to survive dispatch on the SUCCESS arm; got {:?}",
            resp.headers
        );
    }

    #[test]
    fn handle_dispatches_the_json_codec_and_round_trips_the_field() {
        let d = GrpcDispatcher::new("test.EchoService").method("Echo", echo);
        let body = serde_json::to_vec(&TestMsg { text: "hi".to_string() }).unwrap();
        let request = test_req(
            "/test.EchoService/Echo",
            vec![(CODEC_HEADER.to_string(), "json".to_string())],
            body,
        );
        let params = crate::router::Params::from_pairs(vec![]);
        let mut req = Req { request: &request, params: &params, ctx: crate::ctx::Ctx::new() };
        let resp = d.handle(&mut req);
        assert!(resp.headers.contains(&(STATUS_HEADER.to_string(), "0".to_string())));
        let out: TestMsg = serde_json::from_slice(&resp.body.unwrap()).unwrap();
        assert_eq!(out.text, "hi", "the JSON codec must round-trip the field, not just the status");
    }
}
