//! Boogy SDK — building blocks for hand-written and generated APIs.
//!
//! See [README](https://github.com/Boogy-ai/boogy-sdk/tree/main/crates/boogy-sdk)
//! for the full authoring guide. The short version:
//!
//! ```ignore
//! mod bindings {
//!     wit_bindgen::generate!({ world: "service", path: "../../boogy-wit/wit" });
//! }
//! boogy_sdk::wit_glue!(bindings, TodoApi);
//!
//! use boogy_sdk::Api;
//!
//! struct TodoApi;
//!
//! impl Api for TodoApi {
//!     fn init_tables() {
//!         create_table_from(&Table::new("todos").text("title").boolean("done"));
//!     }
//!     fn build_router() -> Router {
//!         Router::new().get("/api/todos", list_todos)
//!     }
//! }
//!
//! #[derive(Serialize)]
//! struct TodosCount { count: u64 }
//!
//! fn list_todos(_req: &mut Req<'_>) -> Result<Json<TodosCount>, ApiError> {
//!     let (_rows, total) = find_all_rows("todos")?;
//!     Ok(Json(TodosCount { count: total }))
//! }
//! ```
//!
//! # Modules
//!
//! - [`json`] — serde + serde_json re-exports
//! - [`response`] — HTTP response builders (ok, created, not_found, etc.)
//! - [`router`] — declarative request routing with path params
//! - [`rpc`] — JSON-RPC 2.0 envelope, error type, response helpers
//! - [`store`] — typed row accessors, table/query builders

// Handler/dispatch tables store fn-pointer and boxed-closure types whose full
// spelling is inherently wide; naming each as a `type` alias adds indirection
// without clarity.
#![allow(clippy::type_complexity)]

pub mod api_keys;
pub mod ctx;
pub mod error;
pub mod extract;
pub mod glue;
pub mod idempotency;
pub mod ids;
pub mod job_router;
pub mod jobs;
pub mod json;
pub mod model;
pub mod log;
pub mod mcp;
pub mod pagination;
pub mod peer;
pub mod query;
pub mod relations;
pub mod request_state;
pub mod response;
pub mod router;
pub mod rpc;
pub mod schema_resolve;
pub mod secrets;
pub mod signing;
pub mod spec;
pub mod store;
pub mod vector;
pub mod websockets;

pub use boogy_sdk_macros::job;
pub use boogy_sdk_macros::Model;
pub use ctx::Ctx;
pub use error::{parse_body, validate_body, ApiError};
// Response wrappers and router types — re-exported so authoring code
// can write `use boogy_sdk::{Json, Created, NoContent, Req, Router}`
// instead of reaching for the macro-emitted crate-root names. The
// per-crate `auth::*` namespace is generated by `wit_glue!` and lives
// only in the user crate's root (see AGENTS.md §"Names available").
pub use response::{Created, HttpResponse, Json, NoContent, Redirect};
pub use schema_resolve::{resolve as resolve_indices, Diagnostic};
pub use router::{Req, Router};
pub use store::{Row, StoreError, Table};
// Typed extractor types and trait — re-exported so handlers can write
// `fn h(Path(id): Path<u64>, …)` with a single `use boogy_sdk::*` import.
// `Json` is intentionally omitted here — it's already exported above from
// `response` and the same type implements `FromRequest` via `extract`.
pub use extract::{FromRequest, Path, Query, Principal};
pub use job_router::{JobContext, JobError, JobRegistration, JobRouter};

/// Boogy SDK convention: the column name Boogy-authored APIs
/// use to record the owning principal of a row. The platform's
/// resource-level auth helpers (`owns_resource`, `find_owned`,
/// `load_owned`) take the owner-column name as a parameter so APIs
/// CAN choose otherwise, but using this constant — and the column
/// name it carries — keeps multi-tenant ownership uniform across the
/// fleet, makes audit / migration / billing tooling possible, and
/// removes a small but real source of LLM-author drift.
pub const DEFAULT_OWNER_COL: &str = "owner_principal";

/// Minimal request type used by the router.
/// APIs should convert their WIT HttpRequest into this (the `wit_glue!`
/// macro generates the converter automatically).
pub struct Request {
    pub method: String,
    pub path: String,
    pub headers: Vec<(String, String)>,
    pub body: Option<Vec<u8>>,
    pub path_params: Vec<(String, String)>,
    pub query_params: Vec<(String, String)>,
}

/// Returns the path to the WIT directory (for use in build.rs scripts or wit_bindgen paths).
pub fn wit_path() -> &'static str {
    concat!(env!("CARGO_MANIFEST_DIR"), "/../boogy-wit/wit")
}

/// The trait every Boogy API implements.
///
/// Both methods are associated functions — they describe the API as a
/// whole, not an instance. The `wit_glue!` macro generates an `impl Guest`
/// that calls them in the right order: `init_tables` once on every
/// request (idempotent because each table create is idempotent) and
/// `build_router` per request to dispatch to handlers.
///
/// # Example
///
/// ```ignore
/// impl boogy_sdk::Api for MyApi {
///     fn init_tables() {
///         create_table_from(&Table::new("users").text("email"));
///     }
///
///     fn build_router() -> Router {
///         Router::new()
///             .get("/api/users", list_users)
///             .post("/api/users", create_user)
///     }
/// }
/// ```
pub trait Api {
    /// Idempotent table creation. Default is a no-op for APIs with no tables.
    fn init_tables() {}

    /// Build the request router. Called per request; cheap to construct.
    fn build_router() -> router::Router;

    /// Build the job router for this API. Default: empty (HTTP-only APIs).
    /// Apps that handle background jobs override this with
    /// `JobRouter::new().exact(...).prefix(...)`.
    fn build_job_router() -> JobRouter { JobRouter::new() }
}
